package biz.digitalhouse.integration.v3;

/**
 * @author Vitalii Babenko
 *         on 28.02.2016.
 */
public enum GeneralSettingKey {

    ASYNCHRONOUS_REQUEST_RETRY_MAX_PROCESS_HOURS("ASYNCHRONOUS_REQUEST_RETRY.MAX_PROCESS_HOURS"),
    ASYNCHRONOUS_REQUEST_RETRY_DELAY_BETWEEN_ATTEMPTS_IN_MINUTES("ASYNCHRONOUS_REQUEST_RETRY.DELAY_BETWEEN_ATTEMPTS_IN_MINUTES"),

    REQUEST_RETRY_MAX_ATTEMPT_NUMBER("REQUEST_RETRY.MAX_ATTEMPT_NUMBER"),
    REQUEST_RETRY_DELAY_BETWEEN_ATTEMPTS("REQUEST_RETRY.DELAY_BETWEEN_ATTEMPTS"),
    SERVICE_SOCKET_TIMEOUT_SECONDS("SERVICE_SOCKET_TIMEOUT.SECONDS"),
    FAST_BINGO_REQUEST_RETRY_MAX_ATTEMPT_NUMBER("FAST_BINGO_REQUEST_RETRY.MAX_ATTEMPT_NUMBER"),
    FAST_BINGO_REQUEST_RETRY_DELAY_BETWEEN_ATTEMPTS("FAST_BINGO_REQUEST_RETRY.DELAY_BETWEEN_ATTEMPTS_MILLISECOND"),
    BINGO_ASYNCHRONOUS_REQUEST_RETRY_MAX_PROCESS_MINUTES("BINGO_ASYNCHRONOUS_REQUEST_RETRY.MAX_PROCESS_MINUTES"),
    BINGO_ASYNCHRONOUS_REQUEST_RETRY_MAX_PROCESS_HOURS("BINGO_ASYNCHRONOUS_REQUEST_RETRY.MAX_PROCESS_HOURS"),
    BINGO_ASYNCHRONOUS_REQUEST_RETRY_MAX_ATTEMPT_NUMBER("BINGO_ASYNCHRONOUS_REQUEST_RETRY.MAX_ATTEMPT_NUMBER"),

    OPERATOR_CONFIGURATIONS("OPERATOR_CONFIGURATIONS"),
    CONFIG_DOUBLE_PROCESS_TIMEOUT("DOUBLE_PROCESS.TIMEOUT_BY_REPEAT.MILLISECOND"),
    CONFIG_DOUBLE_PROCESS_REPEAT("DOUBLE_PROCESS.REPEAT.COUNT"),

    PROVIDER_LOGIN("PROVIDER_LOGIN"),
    PROVIDER_PASSWORD("PROVIDER_PASSWORD"),
    OPERATOR_URL("OPERATOR_URL"),
    PROTOCOL("PROTOCOL"),

    OPERATOR_LOGIN("OPERATOR_LOGIN"),
    OPERATOR_PASS("OPERATOR_PASSWORD"),

    BINGO_TRANSACTION_REPORT_PORTION("BINGO_TRANSACTION_REPORT_PORTION");

    private String val;

    GeneralSettingKey(String val) {
        this.val = "INTEGRATION.CG_API." + val;
    }

    public String key() {
        return this.val;
    }

}
